# Use an official Node runtime as a parent image
FROM node:21.5.0

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY **package.json .

# Install dependencies
RUN npm install

# Copy the remaining application code to the working directory
COPY . .

# Expose port 3000 for development server
EXPOSE 3000

# Start the React development server with live reloading
CMD ["npm", "start"]
